livery = {
	{"F18C_afterburn",	DIFFUSE			,	"f18c_afterburn", true};
	{"f18c2",	DIFFUSE			,	"f18c_2_dif", false};
	{"f18c2",	NORMAL_MAP			,	"f18c_2_nm", false};
	{"f18c2",	ROUGHNESS_METALLIC			,	"f18c_2_dif_roughmet", true};
	{"f18c2",	DAMAGE				,	"f18c_2_damage", true};
	{"f18c2",	10,	"f18c_2_damage_nm", true};
	{"F18C_SKELETON",	DIFFUSE			,	"f18c_skeleton_diff", true};
	{"F18C_SKELETON",	DAMAGE				,	"f18c_skeleton_damage", true};
	{"f18c2",	DIFFUSE			,	"f18c_2_dif", false};
	{"f18c2",	NORMAL_MAP			,	"f18c_2_nm", false};
	{"f18c2",	ROUGHNESS_METALLIC			,	"f18c_2_dif_roughmet", true};
	{"f18c2",	DAMAGE				,	"f18c_2_damage", true};
	{"f18c2",	10,	"f18c_2_damage_nm", true};
	{"f18c1",	DIFFUSE			,	"f18c_1_dif", false};
	{"f18c1",	NORMAL_MAP			,	"f18c_1_nm", true};
	{"f18c1",	ROUGHNESS_METALLIC			,	"f18c_1_dif_roughmet", true};
	{"f18c1",	DAMAGE				,	"f18c_damage", true};
	{"f18c1",	10,	"f18c_damage_nm", true};
	{"F18C_SKELETON",	DIFFUSE			,	"f18c_skeleton_diff", true};
	{"F18C_SKELETON",	DAMAGE				,	"f18c_skeleton_damage", true};
	{"Pilot_F18_Body",	DIFFUSE			,	"pilot_f18", true};
	{"Pilot_F18_Body",	NORMAL_MAP			,	"pilot_f18_nm", true};
	{"Pilot_F18_Body",	ROUGHNESS_METALLIC			,	"pilot_f18_roughmet", true};
	{"F18C_WISP",	DIFFUSE			,	"f18c_wisp_diff", true};
	{"Pilot_F18_Head",	DIFFUSE			,	"pilot_f18_head", true};
	{"Pilot_F18_Head",	NORMAL_MAP			,	"pilot_f18_head_nm", true};
	{"Pilot_F18_Head",	ROUGHNESS_METALLIC			,	"pilot_f18_head_roughmet", true};
	{"pilot_F18_visor_belt",	DIFFUSE			,	"pilot_f18_visor", true};
	{"pilot_F18_visor_belt",	NORMAL_MAP			,	"pilot_f18_visor_nm", true};
	{"pilot_F18_visor_belt",	ROUGHNESS_METALLIC			,	"pilot_f18_visor_roughmet", true};
	{"f18c_wheel_101",	DIFFUSE			,	"f18c_wheel", true};
	{"f18c_wheel_101",	NORMAL_MAP			,	"f18c_wheel_nm", true};
	{"f18c_wheel_101",	ROUGHNESS_METALLIC			,	"f18c_wheel_roughmet", true};
	{"f18c_wheel_101",	DAMAGE				,	"f18c_wheel_damage", true};
	{"f18c_wheel_103",	DIFFUSE			,	"f18c_wheel", true};
	{"f18c_wheel_103",	NORMAL_MAP			,	"f18c_wheel_nm", true};
	{"f18c_wheel_103",	ROUGHNESS_METALLIC			,	"f18c_wheel_roughmet", true};
	{"f18c_wheel_103",	DAMAGE				,	"f18c_wheel_damage", true};
	{"pilot_F18_patch",	DIFFUSE			,	"pilot_f18_patch", true};
	{"pilot_F18_patch",	NORMAL_MAP			,	"pilot_f18_patch_nm", true};
	{"pilot_F18_patch",	ROUGHNESS_METALLIC			,	"pilot_f18_patch_roughmet", true};
	{"pilot_F18_helmet_details",	DIFFUSE			,	"pilot_f18_helmet_details", true};
	{"pilot_F18_helmet_details",	NORMAL_MAP			,	"pilot_f18_helmet_details_nm", true};
	{"pilot_F18_helmet_details",	ROUGHNESS_METALLIC			,	"pilot_f18_helmet_details_roughmet", true};
	{"f18c_wheel_102",	DIFFUSE			,	"f18c_wheel", true};
	{"f18c_wheel_102",	NORMAL_MAP			,	"f18c_wheel_nm", true};
	{"f18c_wheel_102",	ROUGHNESS_METALLIC			,	"f18c_wheel_roughmet", true};
	{"f18c_wheel_102",	DAMAGE				,	"f18c_wheel_damage", true};
	{"F18C_afterburn_bok",	DIFFUSE			,	"f18c_afterburn", true};
	{"F18C_afterburn_bok",	SELF_ILLUMINATION	,	"f18c_afterburn", true};
	{"f18c2",	DIFFUSE			,	"f18c_2_dif", false};
	{"f18c2",	NORMAL_MAP			,	"f18c_2_nm", true};
	{"f18c2",	ROUGHNESS_METALLIC			,	"f18c_2_dif_roughmet", true};
	{"f18c2",	DAMAGE				,	"f18c_2_damage", true};
	{"f18c2",	10,	"f18c_2_damage_nm", true};
	{"F18C_headlight_L",	DIFFUSE			,	"f18c_bano", true};
	{"f18c2",	DIFFUSE			,	"f18c_2_dif", false};
	{"f18c2",	NORMAL_MAP			,	"f18c_2_nm", true};
	{"f18c2",	ROUGHNESS_METALLIC			,	"f18c_2_dif_roughmet", true};
	{"f18c2",	DAMAGE				,	"f18c_2_damage", true};
	{"f18c2",	10,	"f18c_2_damage_nm", true};
	{"f18C_headlight_band_f",	DIFFUSE			,	"f18c_bano", true};
	{"f18C_headlight_band_f",	SELF_ILLUMINATION	,	"f18c_bano", true};
	{"f18c_glass",	DIFFUSE			,	"f18c_glass", true};
	{"f18c_glass",	ROUGHNESS_METALLIC			,	"f18c_glass_roughmet", true};
	{"f18c_glass",	DAMAGE				,	"f18c_glass_damage", true};
	{"f18c1",	DIFFUSE			,	"f18c_1_dif", false};
	{"f18c1",	NORMAL_MAP			,	"f18c_1_nm", true};
	{"f18c1",	ROUGHNESS_METALLIC			,	"f18c_1_dif_roughmet", true};
	{"f18c1",	DAMAGE				,	"f18c_damage", true};
	{"f18c1",	10,	"f18c_damage_nm", true};
	{"cockpit_f18c",	DIFFUSE			,	"f18c_cockpit_dif", true};
	{"cockpit_f18c",	ROUGHNESS_METALLIC			,	"f18c_cockpit_dif_roughmet", true};
	{"F18C_afterburn",	DIFFUSE			,	"f18c_afterburn", true};
	{"F18C_WISP",	DIFFUSE			,	"f18c_wisp_diff", true};
	{"f18c_ladder",	DIFFUSE			,	"f18c_ladder_dif", true};
	{"f18c_ladder",	ROUGHNESS_METALLIC			,	"f18c_ladder_dif_roughmet", true};
	{"f18c1",	DIFFUSE			,	"f18c_1_dif", false};
	{"f18c1",	NORMAL_MAP			,	"f18c_1_nm", true};
	{"f18c1",	ROUGHNESS_METALLIC			,	"f18c_1_dif_roughmet", true};
	{"f18c1",	DAMAGE				,	"f18c_damage", true};
	{"f18c1",	10,	"f18c_damage_nm", true};
	{"P51D_Flame F11",	DIFFUSE			,	"flame_f11", true};
	{"f18C_headlight_band_banno",	DIFFUSE			,	"f18c_bano", true};
	{"f18c_Glass",	DIFFUSE			,	"f18c_canopy-glass", true};
	{"F18C_Brake_pads",	DIFFUSE			,	"f18c_brake_pads_dif", true};
	{"F18C_Brake_pads",	NORMAL_MAP			,	"f18c_brake_pads_nm", true};
	{"F18C_Brake_pads",	ROUGHNESS_METALLIC			,	"f18c_brake_pads_dif_roughmet", true};
	{"F18C_SKELETON",	DIFFUSE			,	"f18c_skeleton_diff", true};
	{"F18C_SKELETON",	DAMAGE				,	"f18c_skeleton_damage", true};
	{"F18C_SKELETON",	DIFFUSE			,	"f18c_skeleton_diff", true};
	{"F18C_SKELETON",	DAMAGE				,	"f18c_skeleton_damage", true};
	{"f18C_headlight_band",	DIFFUSE			,	"f18c_bano", true};
	{"f18C_headlight_band",	SELF_ILLUMINATION	,	"f18c_bano", true};
	{"P51D_Flame F12",	DIFFUSE			,	"flame_f12", true};
	{"f18c_glass_ils",	DIFFUSE			,	"f18c_glass", true};
	{"f18c_glass_ils",	ROUGHNESS_METALLIC			,	"f18c_glass_roughmet", true};
	{"f18c_glass_ils",	DAMAGE				,	"f18c_glass_damage", true};
	{"P51D_Flame F14",	DIFFUSE			,	"flame_f14", true};
	{"f18C_headlight_R",	DIFFUSE			,	"f18c_bano", true};
	{"F18C_omni_banno_192",	DIFFUSE			,	"f18c_bano", true};
	{"pilot_F18_visor_glass",	DIFFUSE			,	"pilot_f18_visor", true};
	{"pilot_F18_visor_glass",	NORMAL_MAP			,	"pilot_f18_visor_nm", true};
	{"pilot_F18_visor_glass",	ROUGHNESS_METALLIC			,	"pilot_f18_visor_roughmet", true};
	{"f18c_stay",	DIFFUSE			,	"f18c_1_diff_stay_dif", true};
	{"f18c_stay",	NORMAL_MAP			,	"f18c_1_diff_stay_nm", true};
	{"f18c_stay",	ROUGHNESS_METALLIC			,	"f18c_1_diff_stay_dif_roughmet", true};
	{"P51D_Flame12",	DIFFUSE			,	"flame_12", true};
	{"F18C_rulezh",	DIFFUSE			,	"f18c_bano", true};
	{"ANA_SQ_228",	DIFFUSE			,	"ana_sq_228_diff", true};
	{"ANA_SQ_228",	NORMAL_MAP			,	"ana_sq_228_nm", true};
	{"ANA_SQ_228",	ROUGHNESS_METALLIC			,	"ana_sq_228_diff_roughmet", true};
	{"P51D_Flame F13",	DIFFUSE			,	"flame_f13", true};
	{"F18C_headlight_22",	DIFFUSE			,	"f18c_bano", true};
	{"F18C_aoa",	DIFFUSE			,	"f18c_bano", true};
	{"pilot_F18_helmet_hmd",	DIFFUSE			,	"pilot_f18_helmet_hmd", false};
	{"pilot_F18_helmet_hmd",	NORMAL_MAP			,	"pilot_f18_helmet_hmd_nm", true};
	{"pilot_F18_helmet_hmd",	ROUGHNESS_METALLIC			,	"pilot_f18_helmet_hmd_roughmet", true};
	{"f18C_headlight_KIL",	DIFFUSE			,	"f18c_bano", true};
	{"pilot_F18_helmet_details",	DIFFUSE			,	"pilot_f18_helmet_details", true};
	{"pilot_F18_helmet_details",	NORMAL_MAP			,	"pilot_f18_helmet_details_nm", true};
	{"pilot_F18_helmet_details",	ROUGHNESS_METALLIC			,	"pilot_f18_helmet_details_roughmet", true};
	{"cockpit_f18c_2",	DIFFUSE			,	"f18c_cockpit_2_dif", true};
	{"cockpit_f18c_2",	ROUGHNESS_METALLIC			,	"f18c_cockpit_2_dif_roughmet", true};
	{"cockpit_f18c_n",	DIFFUSE			,	"f18c_cockpit_dif", true};
	{"cockpit_f18c_n",	ROUGHNESS_METALLIC			,	"f18c_cockpit_dif_roughmet", true};
	{"Pilot_F18_Body",	DIFFUSE			,	"pilot_f18", true};
	{"Pilot_F18_Body",	NORMAL_MAP			,	"pilot_f18_nm", true};
	{"Pilot_F18_Body",	ROUGHNESS_METALLIC			,	"pilot_f18_roughmet", true};
	{"P51D_Flame14",	DIFFUSE			,	"flame_14", true};
	{"Pylon_AAQ28L",	DIFFUSE			,	"pylon_aaq28l_diff", true};
	{"Pylon_AAQ28L",	NORMAL_MAP			,	"pylon_aaq28l_nm", true};
	{"Pylon_AAQ28L",	ROUGHNESS_METALLIC			,	"pylon_aaq28l_diff_roughmet", true};
	{"pilot_F18_helmet",	DIFFUSE			,	"pilot_f18_helmet", true};
	{"pilot_F18_helmet",	NORMAL_MAP			,	"pilot_f18_helmet_nm", true};
	{"pilot_F18_helmet",	ROUGHNESS_METALLIC			,	"pilot_f18_helmet_roughmet", true};
	{"F18C_headlight",	DIFFUSE			,	"f18c_bano", true};
	{"P51D_Flame13",	DIFFUSE			,	"flame_13", true};
	{"f18c_glass",	DIFFUSE			,	"f18c_glass", true};
	{"f18c_glass",	ROUGHNESS_METALLIC			,	"f18c_glass_roughmet", true};
	{"f18c_glass",	DAMAGE				,	"f18c_glass_damage", true};
	{"P51D_Flame11",	DIFFUSE			,	"flame_11", true};
	{"F18C_aoa_dammy",	DIFFUSE			,	"f18c_bano", true};
	{"F18C_headlight_dammy",	DIFFUSE			,	"f18c_bano", true};
	{"f18C_headlight_R_dammy",	DIFFUSE			,	"f18c_bano", true};
	{"F18C_headlight_L_dammy",	DIFFUSE			,	"f18c_bano", true};
	{"F18C_omni_banno_192_dammy",	DIFFUSE			,	"f18c_bano", true};
	{"f18C_headlight_KIL_dammy",	DIFFUSE			,	"f18c_bano", true};
	{"f18c2_number_X",	DIFFUSE			,	"f18c_2_dif", false};
	{"f18c2_number_X",	ROUGHNESS_METALLIC			,	"f18c_2_dif_roughmet", true};
	{"f18c2_number_X",	DECAL				,	"empty", true};
	{"f18c2_number_X",	DAMAGE				,	"f18c_2_damage", true};
	{"f18c1_number_F",	DIFFUSE			,	"f18c_1_dif", false};
	{"f18c1_number_F",	ROUGHNESS_METALLIC			,	"f18c_1_dif_roughmet", true};
	{"f18c1_number_F",	DECAL				,	"empty", true};
	{"f18c1_number_F",	DAMAGE				,	"f18c_damage", true};
	{"f18c2_kil_left",	DIFFUSE			,	"f18c_2_dif", false};
	{"f18c2_kil_left",	ROUGHNESS_METALLIC			,	"f18c_2_dif_roughmet", true};
	{"f18c2_kil_left",	DECAL				,	"f18c_bort_number2", true};
	{"f18c2_kil_left",	DAMAGE				,	"f18c_2_damage", true};
	{"f18c2_number_X",	DIFFUSE			,	"f18c_2_dif", false};
	{"f18c2_number_X",	ROUGHNESS_METALLIC			,	"f18c_2_dif_roughmet", true};
	{"f18c2_number_X",	DECAL				,	"empty", true};
	{"f18c2_number_X",	DAMAGE				,	"f18c_2_damage", true};
	{"f18c1_number_nose_left",	DIFFUSE			,	"f18c_1_dif", false};
	{"f18c1_number_nose_left",	ROUGHNESS_METALLIC			,	"f18c_1_dif_roughmet", true};
	{"f18c1_number_nose_left",	DECAL				,	"f18c_bort_number2", true};
	{"f18c1_number_nose_left",	DAMAGE				,	"f18c_damage", true};
	{"f18c2_kil_right",	DIFFUSE			,	"f18c_2_dif", false};
	{"f18c2_kil_right",	ROUGHNESS_METALLIC			,	"f18c_2_dif_roughmet", true};
	{"f18c2_kil_right",	DECAL				,	"f18c_bort_number2", true};
	{"f18c2_kil_right",	DAMAGE				,	"f18c_2_damage", true};
	{"f18c1_number_nose_right",	DIFFUSE			,	"f18c_1_dif", false};
	{"f18c1_number_nose_right",	ROUGHNESS_METALLIC			,	"f18c_1_dif_roughmet", true};
	{"f18c1_number_nose_right",	DECAL				,	"f18c_bort_number2", true};
	{"f18c1_number_nose_right",	DAMAGE				,	"f18c_damage", true};
	
	{"FPU_8A", 0 ,"FPU_8A",false};
	{"FPU_8A", 2 ,"FPU_8A_Diff_RoughMet",true};
	
}

name = "Dragon Riders"
countries = {"USA",}